Dev 1
stepancar-web-programming/2022-fall-lab-portfolio-zaycev-danil-dmitrievich pull request #1
Opened 2022-12-18 23:48 UTC by blabla9111

2022-12-20 01:10 UTC, stepancar requested changes
Пожалуйста отформатируйте все файлы перед отправкой на ревью

2022-12-22 16:36 UTC, blabla9111 commented
> Пожалуйста отформатируйте все файлы перед отправкой на ревью

Отформатировала, проверьте, пожалуйста, @stepancar

2022-12-23 06:55 UTC, stepancar commented on package.json
> +  "dependencies": {
@blabla9111 пожалуйста, не забудьте про разделение зависимостей

2022-12-23 06:56 UTC, stepancar commented on package.json
> +    "lint:fix": "eslint ./src --fix",
заметете, тут есть дубликат. При усложении параметров вы заметите что вам нужно поддерживать две одинаковые строки, значит есть возможность прийти к неконсистентному состоянию

2022-12-23 07:04 UTC, stepancar commented
@blabla9111 , супер. Спасибо.
Хорошо что разобрались с навигацией. 
Но хотелось бы чтобы вы понимали почему не работала навигация сначала и как то, что я вам предложил сделать помогло.
Подготовьтесь плиз, расскажите во время перерыва на паре и баллы ваши!

2022-12-23 07:04 UTC, stepancar approved these changes

2022-12-26 00:33 UTC, stepancar commented
@blabla9111 , мержите пожалуйста

2022-12-26 10:07 UTC, merged